import type { Server } from 'socket.io';
import { verifyAccess } from '../auth/tokens.js';
import { prisma } from '../database/prisma.js';
import { projectFor } from '../services/access.js';
let io: Server | undefined;
const online = new Map<string, number>();
export function installSockets(server: Server) { io = server; server.use((socket, next) => { try { socket.data.user = verifyAccess(socket.handshake.auth.token); next(); } catch { next(new Error('unauthorized')); } }); server.on('connection', async socket => { const user = socket.data.user; online.set(user.id, (online.get(user.id) ?? 0) + 1); server.to('admins').emit('presence:count', online.size); if (user.role === 'ADMIN') socket.join('admins'); socket.join(`user:${user.id}`); const where = user.role === 'ADMIN' ? {} : user.role === 'PROJECT_MANAGER' ? { project: { createdById: user.id } } : { task: { assignedDeveloperId: user.id } }; const missed = await prisma.activity.findMany({ where, orderBy: { createdAt: 'desc' }, take: 20, include: { actor: { select: { name: true } }, task: { select: { title: true } } } }); socket.emit('activity:missed', missed.reverse()); socket.on('project:join', async (projectId: string) => { if (user.role !== 'DEVELOPER') { try { await projectFor(user, projectId); socket.join(`project:${projectId}`); } catch { /* do not join */ } } }); socket.on('project:leave', (projectId: string) => socket.leave(`project:${projectId}`)); socket.on('disconnect', () => { const count = (online.get(user.id) ?? 1) - 1; count ? online.set(user.id, count) : online.delete(user.id); server.to('admins').emit('presence:count', online.size); }); }); }
export const emitActivity = (activity: unknown, projectId: string, developerId?: string | null) => { io?.to(`project:${projectId}`).emit('activity:new', activity); if (developerId) io?.to(`user:${developerId}`).emit('activity:new', activity); io?.to('admins').emit('activity:new', activity); };
export const emitNotification = (userId: string, notification: unknown, unreadCount: number) => io?.to(`user:${userId}`).emit('notification:update', { notification, unreadCount });
