import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { Prisma, Role, TaskStatus, Priority, ActivityType, NotificationType } from '@prisma/client';
import { prisma } from '../database/prisma.js';
import { authenticate, allow } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { AppError } from '../errors/app-error.js';
import { hashToken, signAccess, signRefresh, verifyRefresh } from '../auth/tokens.js';
import { env } from '../config/env.js';
import { projectFor, taskFor } from '../services/access.js';
import { emitActivity, emitNotification } from '../realtime/socket.js';

const id = z.string().cuid(); const cookie = { httpOnly: true, secure: env.COOKIE_SECURE === 'true', sameSite: 'lax' as const, path: '/api/auth', maxAge: 7 * 86400000 };
const taskInput = z.object({ title: z.string().min(1).max(160), description: z.string().min(1).max(5000), assignedDeveloperId: id.optional(), priority: z.nativeEnum(Priority), dueDate: z.coerce.date() });
export const api = Router();
api.get('/health', (_req, res) => res.json({ data: { status: 'ok' } }));

api.post('/auth/login', validate(z.object({ body: z.object({ email: z.string().email(), password: z.string().min(8) }), params: z.object({}), query: z.object({}) })), async (req, res) => { const user = await prisma.user.findUnique({ where: { email: req.body.email } }); if (!user || !(await bcrypt.compare(req.body.password, user.passwordHash))) throw new AppError(401, 'INVALID_CREDENTIALS', 'Invalid email or password'); const payload = { id: user.id, role: user.role, name: user.name }; const refresh = signRefresh(payload); await prisma.refreshToken.create({ data: { userId: user.id, tokenHash: hashToken(refresh), expiresAt: new Date(Date.now() + 7 * 86400000) } }); res.cookie('refreshToken', refresh, cookie).json({ data: { accessToken: signAccess(payload), user: payload } }); });
api.post('/auth/refresh', async (req, res) => { const raw = req.cookies?.refreshToken; if (!raw) throw new AppError(401, 'UNAUTHENTICATED', 'Refresh token is required'); let token; try { token = verifyRefresh(raw); } catch { throw new AppError(401, 'UNAUTHENTICATED', 'Invalid refresh token'); } const stored = await prisma.refreshToken.findUnique({ where: { tokenHash: hashToken(raw) }, include: { user: true } }); if (!stored || stored.revokedAt || stored.expiresAt < new Date()) throw new AppError(401, 'UNAUTHENTICATED', 'Refresh token is revoked or expired'); await prisma.refreshToken.update({ where: { id: stored.id }, data: { revokedAt: new Date() } }); const payload = { id: stored.user.id, role: stored.user.role, name: stored.user.name }; const replacement = signRefresh(payload); await prisma.refreshToken.create({ data: { userId: token.id, tokenHash: hashToken(replacement), expiresAt: new Date(Date.now() + 7 * 86400000) } }); res.cookie('refreshToken', replacement, cookie).json({ data: { accessToken: signAccess(payload), user: payload } }); });
api.post('/auth/logout', async (req, res) => { const raw = req.cookies?.refreshToken; if (raw) await prisma.refreshToken.updateMany({ where: { tokenHash: hashToken(raw), revokedAt: null }, data: { revokedAt: new Date() } }); res.clearCookie('refreshToken', { ...cookie, maxAge: undefined }).status(204).send(); });

api.use(authenticate);
api.get('/users', allow(Role.ADMIN), async (_req, res) => res.json({ data: await prisma.user.findMany({ select: { id: true, name: true, email: true, role: true } }) }));
api.post('/users', allow(Role.ADMIN), validate(z.object({ body: z.object({ name: z.string().min(1), email: z.string().email(), password: z.string().min(12), role: z.nativeEnum(Role) }), params: z.object({}), query: z.object({}) })), async (req, res) => { const passwordHash = await bcrypt.hash(req.body.password, 12); res.status(201).json({ data: await prisma.user.create({ data: { ...req.body, passwordHash }, select: { id: true, name: true, email: true, role: true } }) }); });
api.get('/clients', allow(Role.ADMIN, Role.PROJECT_MANAGER), async (_req, res) => res.json({ data: await prisma.client.findMany({ orderBy: { name: 'asc' } }) }));
api.post('/clients', allow(Role.ADMIN), validate(z.object({ body: z.object({ name: z.string().min(1).max(160) }), params: z.object({}), query: z.object({}) })), async (req, res) => res.status(201).json({ data: await prisma.client.create({ data: req.body }) }));
api.get('/projects', async (req, res) => { const where = req.user!.role === Role.ADMIN ? {} : req.user!.role === Role.PROJECT_MANAGER ? { createdById: req.user!.id } : { tasks: { some: { assignedDeveloperId: req.user!.id } } }; res.json({ data: await prisma.project.findMany({ where, include: { client: true, _count: { select: { tasks: true } } } }) }); });
api.post('/projects', allow(Role.ADMIN, Role.PROJECT_MANAGER), validate(z.object({ body: z.object({ name: z.string().min(1), clientId: id }), params: z.object({}), query: z.object({}) })), async (req, res) => res.status(201).json({ data: await prisma.project.create({ data: { ...req.body, createdById: req.user!.id } }) }));
api.get('/projects/:projectId', validate(z.object({ body: z.unknown(), params: z.object({ projectId: id }), query: z.object({}) })), async (req, res) => { const projectId = req.params.projectId as string; if (req.user!.role === Role.DEVELOPER) { const exists = await prisma.task.findFirst({ where: { projectId, assignedDeveloperId: req.user!.id } }); if (!exists) throw new AppError(403, 'FORBIDDEN', 'Project access denied'); } else await projectFor(req.user!, projectId); res.json({ data: await prisma.project.findUniqueOrThrow({ where: { id: projectId }, include: { client: true } }) }); });
api.post('/projects/:projectId/tasks', allow(Role.ADMIN, Role.PROJECT_MANAGER), validate(z.object({ body: taskInput, params: z.object({ projectId: id }), query: z.object({}) })), async (req, res) => { const projectId = req.params.projectId as string; await projectFor(req.user!, projectId); if (req.body.assignedDeveloperId) { const dev = await prisma.user.findUnique({ where: { id: req.body.assignedDeveloperId } }); if (!dev || dev.role !== Role.DEVELOPER) throw new AppError(400, 'VALIDATION_ERROR', 'Assignee must be a developer'); } const task = await prisma.$transaction(async tx => { const created = await tx.task.create({ data: { ...req.body, projectId } }); if (created.assignedDeveloperId) await tx.notification.create({ data: { recipientId: created.assignedDeveloperId, taskId: created.id, type: NotificationType.TASK_ASSIGNED, message: `You were assigned: ${created.title}` } }); return created; }); if (task.assignedDeveloperId) { const n = await prisma.notification.findFirst({ where: { taskId: task.id, recipientId: task.assignedDeveloperId }, orderBy: { createdAt: 'desc' } }); const unreadCount = await prisma.notification.count({ where: { recipientId: task.assignedDeveloperId, readAt: null } }); emitNotification(task.assignedDeveloperId, n, unreadCount); } res.status(201).json({ data: task }); });
api.get('/tasks', validate(z.object({ body: z.unknown(), params: z.object({}), query: z.object({ status: z.nativeEnum(TaskStatus).optional(), priority: z.nativeEnum(Priority).optional(), dueFrom: z.coerce.date().optional(), dueTo: z.coerce.date().optional(), projectId: id.optional() }) })), async (req, res) => { const q = req.query as any; const where: Prisma.TaskWhereInput = { ...(q.status && { status: q.status }), ...(q.priority && { priority: q.priority }), ...(q.dueFrom || q.dueTo ? { dueDate: { ...(q.dueFrom && { gte: q.dueFrom }), ...(q.dueTo && { lte: q.dueTo }) } } : {}), ...(q.projectId && { projectId: q.projectId }) }; if (req.user!.role === Role.PROJECT_MANAGER) where.project = { createdById: req.user!.id }; if (req.user!.role === Role.DEVELOPER) where.assignedDeveloperId = req.user!.id; res.json({ data: await prisma.task.findMany({ where, include: { project: true, assignedDeveloper: { select: { id: true, name: true } } }, orderBy: req.user!.role === Role.DEVELOPER ? [{ priority: 'desc' }, { dueDate: 'asc' }] : { dueDate: 'asc' } }) }); });
api.patch('/tasks/:taskId/status', validate(z.object({ body: z.object({ status: z.nativeEnum(TaskStatus) }), params: z.object({ taskId: id }), query: z.object({}) })), async (req, res) => { const prior = await taskFor(req.user!, req.params.taskId as string); if (req.user!.role === Role.DEVELOPER && prior.assignedDeveloperId !== req.user!.id) throw new AppError(403, 'FORBIDDEN', 'Task access denied'); const { task, activity, notification } = await prisma.$transaction(async tx => { const task = await tx.task.update({ where: { id: prior.id }, data: { status: req.body.status, isOverdue: req.body.status === TaskStatus.DONE ? false : prior.isOverdue } }); const activity = await tx.activity.create({ data: { projectId: prior.projectId, taskId: prior.id, actorId: req.user!.id, type: ActivityType.TASK_STATUS_CHANGED, previousStatus: prior.status, nextStatus: req.body.status }, include: { actor: { select: { name: true } }, task: { select: { title: true } } } }); let notification = null; if (req.body.status === TaskStatus.IN_REVIEW) notification = await tx.notification.create({ data: { recipientId: prior.project.createdById, taskId: prior.id, type: NotificationType.TASK_IN_REVIEW, message: `${req.user!.name} moved ${prior.title} to In Review` } }); return { task, activity, notification }; }); emitActivity(activity, prior.projectId, prior.assignedDeveloperId); if (notification) emitNotification(notification.recipientId, notification, await prisma.notification.count({ where: { recipientId: notification.recipientId, readAt: null } })); res.json({ data: task }); });
api.get('/activities', async (req, res) => { const where = req.user!.role === Role.ADMIN ? {} : req.user!.role === Role.PROJECT_MANAGER ? { project: { createdById: req.user!.id } } : { task: { assignedDeveloperId: req.user!.id } }; res.json({ data: await prisma.activity.findMany({ where, take: 50, orderBy: { createdAt: 'desc' }, include: { actor: { select: { name: true } }, task: { select: { title: true } } } }) }); });
api.get('/notifications', async (req, res) => res.json({ data: await prisma.notification.findMany({ where: { recipientId: req.user!.id }, orderBy: { createdAt: 'desc' }, take: 30 }), unreadCount: await prisma.notification.count({ where: { recipientId: req.user!.id, readAt: null } }) }));
api.patch('/notifications/:notificationId/read', validate(z.object({ body: z.object({}), params: z.object({ notificationId: id }), query: z.object({}) })), async (req, res) => { const n = await prisma.notification.findFirst({ where: { id: req.params.notificationId as string, recipientId: req.user!.id } }); if (!n) throw new AppError(404, 'NOT_FOUND', 'Notification not found'); const data = await prisma.notification.update({ where: { id: n.id }, data: { readAt: new Date() } }); emitNotification(req.user!.id, data, await prisma.notification.count({ where: { recipientId: req.user!.id, readAt: null } })); res.json({ data }); });
api.patch('/notifications/read-all', async (req, res) => { await prisma.notification.updateMany({ where: { recipientId: req.user!.id, readAt: null }, data: { readAt: new Date() } }); emitNotification(req.user!.id, null, 0); res.status(204).send(); });
